# Generated by Django 5.2.11 on 2026-02-20 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loyaltypointtransaction',
            name='related_booking',
        ),
        migrations.RemoveField(
            model_name='loyaltypointtransaction',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='loyaltypointtransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='loyalty_discount_applied',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='loyalty_points_used',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='owner_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.booking')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.salon')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.salonstaff')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerLoyaltyPoints',
        ),
        migrations.DeleteModel(
            name='FCMToken',
        ),
        migrations.DeleteModel(
            name='LoyaltyPointTransaction',
        ),
        migrations.DeleteModel(
            name='LoyaltyProgram',
        ),
    ]
