# Generated by Django 5.2.11 on 2026-02-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservice',
            name='session_count',
            field=models.IntegerField(default=1),
        ),
    ]
