# Generated by Django 5.2.11 on 2026-02-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_salonservice_session_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservice',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
