# Generated by Django 5.2.11 on 2026-02-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='pin_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
