# Generated by Django 5.2.11 on 2026-03-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='staff_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
